title: Mohamed Aziz Lassoued
logo: assets/PersonalPic.png
description: Electrical automation engineer passionate about PCB design, embedded software, and IoT systems. Explore my projects and technical work.
theme: jekyll-theme-minimal
