title: Mohamed Aziz Lassoued
description: Embedded Systems and Automation Engineering student passionate about PCB design, embedded software, and IoT systems. Explore my projects and technical work.
logo: assets/PersonalPic.png
theme: jekyll-theme-minimal
